//! Prelude for example entities
//!
//! Re-exports common types used by the generated entities.

// Re-export entity models
pub use super::user::Model as User;

// Stub request/response types for the storage trait.
// In a real application, these would be generated by prost from the proto file.

/// Request to get a user by ID
#[derive(Debug, Clone)]
pub struct GetUserRequest {
    pub id: i64,
}

/// Request to create a new user
#[derive(Debug, Clone)]
pub struct CreateUserRequest {
    pub email: String,
    pub name: String,
}

/// Request to list users with pagination
#[derive(Debug, Clone)]
pub struct ListUsersRequest {
    pub page: i32,
    pub page_size: i32,
}

/// Response containing a list of users
#[derive(Debug, Clone)]
pub struct ListUsersResponse {
    pub users: Vec<User>,
    pub total: i32,
}
